### ISSUE TITLE
Feedback & suggestion: routes/hooks/route.js is pretty terse, adding a comment might help newbies   

### ISSUE THREAD

**Issue by andrew-j-roberts** [Elderjs/template#13]
Hi all,  

I'm really happy with the documentation of this project, I spent the morning reading up and plan to use Elder.js for my personal developer site instead of Sapper.  

I got the template up and running but at first I was very confused by the /hooks directory and its associated files. 

E.g. https://github.com/Elderjs/template/blob/master/src/routes/hooks/route.js

I saw an import from @elderjs/elderjs and immediately assumed it was some automagical generation step, but I had noooo idea what this nested hooks directory was for.  

[https://elderjs.netlify.app/hooks](https://elderjs.netlify.app/hooks) 404s... 

I figured it out and laughed after I did, but it took a little longer than I'd like to admit...

<img width="465" alt="2020-09-13_11-44-34" src="https://user-images.githubusercontent.com/46111212/93022517-dafc2780-f5b7-11ea-9af1-c8a7a2fe5742.png">

<img width="1025" alt="2020-09-13_11-52-20" src="https://user-images.githubusercontent.com/46111212/93022520-ddf71800-f5b7-11ea-8a11-a2611c6acccc.png">

P.S. thanks for the awesome framework & this very functional template.

**Comment by nickreese** [comment]
@andrew-j-roberts I totally agree. For new comers this template needs work. Too much magic.

After v1 my goal is to have a super barebones template where everything is obvious and probably a video walkthrough / tutorial with it so that users can extend the template and understand the steps. 

Then a separate blogging template with a bunch of magic and pre configs. 

Always open to feedback or PRs if you see areas for improvement.

**Comment by nickreese** [comment]
@andrew-j-roberts Spent a bit of adding comments and documenting what is going on as a first start to help things easier to digest for beginners: https://github.com/Elderjs/template/commit/209b33b0c6e10ea8d08caf7d489d4ee7f3bf4ad9

Also:

1. removed the data.js files as separate files as that was just confusing. 
1. documented what is going on in the plugin.
1. added two hooks for users to try in the hooks.js.

Let me know if you have other ideas on how to improve.

**Comment by andrew-j-roberts** [comment]
Wow man you work quick — I read through your comments and I certainly think they help show off the data flow in Elder.js, which is where it seems to shine. I'll definitely let you know on here or Twitter if I have any feedback or ideas.
