### ISSUE TITLE
Alternative server (speedy)

### ISSUE THREAD

**Issue by timeshift92** [Elderjs/template#25]
Hello, have not tried using uWebSockets.js instead of express.js (polka.js)
https://github.com/uNetworking/uWebSockets.js

**Comment by nickreese** [comment]
You can use Elder.js with any framework you can get it to work with but we’ll only offer a single solution as a template to limit edge cases and onboarding. 

Also having worked with websockets extensively, this is a bad idea for most use cases unless you’re dealing with real time data and in that case you probably need a different framework than Elder.js.
