### ISSUE TITLE
Blog section not showing for template

### ISSUE THREAD

**Issue by TotalLag** [Elderjs/template#41]
Hi, nice project you have here. I am trying to follow the quickstart and have degit the template then ran `npm run dev` locally on my machine.  I am accessing the site via IP vs `localhost`.

For some reason, I am not able to see the blog section that is suppose to show on Home.

```
<div class="blog">
  <div class="grid grid-cols-1 gap-4 bg-red-400 sm:grid-cols-3">
    {#each data.markdown as blog}
      <BlogTeaser {blog} {link} />
    {/each}
  </div>
</div>
```
This part does not render for me and I can't figure if it's a config, server, or I'm missing something.

**Comment by sw-yx** [comment]
i have just run a degit and install and started from scratch per the readme here, and it renders fine:

![image](https://user-images.githubusercontent.com/6764957/108591255-bdbb5880-73a2-11eb-88a4-cd76ac15720f.png)

you'll need to give us more info to figure this out

**Comment by TotalLag** [comment]
well crap. looks like i had some remnants from https://github.com/meigo/elderjs-tailwind as i wanted to try tailwind with it. starting from scratch and manually installing tailwind seem to have worked better.

my mistake. sorry for wasting your time!
