### ISSUE TITLE
Instructions says to use "npm run dev:server"

### ISSUE THREAD

**Issue by canadaduane** [Elderjs/template#44]
First time user, encountered these instructions:

https://github.com/Elderjs/template/blob/166105d5495839f9f6373a8f5378aaaf06acd470/src/routes/home/Home.svelte#L139

But I think the correct way to start the server in two tabs changed recently.

**Comment by nickreese** [comment]
@canadaduane Thanks for this. Pushed a major update yesterday and forgot the content may be outdated. Changed it elsewhere but missed that. I'll get it fixed.

**Comment by nickreese** [comment]
@canadaduane Thanks again. Just pushed a fix to both of the issues.
