### ISSUE TITLE
Instructions say routes are in `./src/routes/index.js`

### ISSUE THREAD

**Issue by canadaduane** [Elderjs/template#45]
I can't find `./src/routes/index.js`, but this file is mentioned as important here:

https://github.com/Elderjs/template/blame/master/src/routes/blog/getting-started.md#L15

**Comment by nickreese** [comment]
@canadaduane Thanks again. Just pushed a fix to both of the issues.

**Comment by nickreese** [comment]
Overhauled a large amount of the template this afternoon content wise to try and make sure things are clearer. Thanks again.
